spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://198.19.227.58:15201
      authentication: token
      token:  ${VAULT_SECRET}
      kv:
        enabled: true
        backend: secret
        default-context: mysql
  datasource:
    url: ${vault.datasource.user}
    username: ${vault.datasource.username}
    password: ${vault.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: User-Service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 65534
  forward-headers-strategy: framework

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://198.18.0.169:8761/eureka
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.boot: DEBUG
    com.zaxxer.hikari: DEBUG